Modifie la typographie du document
etalab/licence-ouverte pull request #2
Opened 2018-11-22 08:41 UTC by bboulesteix

Cette _pull-request_ ne change pas le texte du document en lui-même, elle n’en modifie que la ponctuation — pour être conforme aux [règles typographiques en vigueur à l’Imprimerie nationale](https://fr.wikipedia.org/wiki/Lexique_des_règles_typographiques_en_usage_à_l%27Imprimerie_nationale).

En gros :

* elle ajoute des accents sur les capitales (`Etat` devient `État`) ;
* elle remplace les apostrophes droites (`'`) par des apostrophes courbes (`’`) ;
* elle ajoute des espaces insécables à l’intérieur des guillemets ;
* elle corrige [la ponctuation des listes](https://github.com/etalab/etalab/blob/master/typographie.md#ponctuation-des-listes).

2018-11-22 09:21 UTC, jdesboeufs commented
T'as renommé le fichier aussi, pas pratique pour le diff ;)

2018-11-22 09:34 UTC, bboulesteix commented
Je sais, je sais, mais je ne trouvais pas `LO.md` suffisamment explicite. J’aurais peut-être dû faire une première _pull-request_ pour modifier le fichier (sans changer son nom) et une seconde, plus tard, pour en changer le nom.

2018-11-22 09:34 UTC, noirbizarre requested changes
Ne pas renommer le fichier (du moins pas avant d'avoir vérifier les liens entrant, comme par exemple le blog Etalab).

2018-11-22 09:39 UTC, bboulesteix commented
Merci pour votre relecture. 👍 

Pour vous répondre :

@jdesboeufs 
Le diff est de retour, puisque je viens de renommer le fichier. 🎉 

@noirbizarre 
Un lien sera affecté par le changement de nom du fichier, il part d’une page du [site Etalab](https://www.etalab.gouv.fr/licence-ouverte-open-licence).

2018-11-22 09:51 UTC, jdesboeufs commented on LO.md
> +Le « Concédant » concède au « Réutilisateur » un droit non exclusif et gratuit de libre  « Réutilisation » de l’«Information » objet de la présente licence, à des fins commerciales ou non, dans le mo
Espace aussi avant Information ;)

2018-11-22 10:00 UTC, noirbizarre commented
Après, honnêtement, je ne connais pas les implications juridiques et légales d'un changement de texte de licence, même si ça n'est que pour des typos :thinking:

2018-11-22 10:12 UTC, bboulesteix commented on LO.md
> +Le « Concédant » concède au « Réutilisateur » un droit non exclusif et gratuit de libre  « Réutilisation » de l’«Information » objet de la présente licence, à des fins commerciales ou non, dans le mo
Bien vu, merci @jdesboeufs. 👀

2018-11-22 10:18 UTC, noirbizarre reviewed
OK sur le principe des changements typographiques.
J'émets par contre plusieurs réserves.

## Réserves juridico-légale:
Je ne connais pas les implications de la renumérotation des titres, de certaines listes et de ces changements typographiques. Outre la modification dans ce dépôt, est-ce qu'il ne faut pas:
- backporter ces modifications sur le document PDF du site Etalab ? (pour éviter d'avoir différentes versions)
- est-ce qu'il y a une procédure particulière pour faire reconnaître cette version modifiée comme la version en vigueur ?

## Réserves techniques:
Markdown est un language voué à être rendu, et certains de ces changements typographiques ne seront visibles (ou pas) qu'en fonction du moteur de rendu (par exemple, certains intègrent par défaut  Typogriphy ou Smartypant qui font automatiquement ce types de changements (https://github.com/mintchaos/typogrify, https://pypi.org/project/smartypants/ et https://daringfireball.net/projects/smartypants/). Ça n'est pas bloquant mais je me demande s'il ne serait pas nécéssaire pour le long terme d'exposer nos règles de gestion du markdown (syntaxe retenue de préférence et règles de rendu)

2018-11-22 10:18 UTC, noirbizarre commented on LO.md
> +* de la communiquer, la reproduire, la copier ;
Je conserverais des `-` pour les tirets, c'est ce qu'on utilise sur tous les textes en markdown pour le moments (ex: https://github.com/etalab/data.gouv.fr/blob/master/CGU.md )
Peut-être qu'il faudra qu'on fasse un fichier `remarkrc` ou autre pour définir nos conventions et pour éviter que ça change au grès des goûts de chaque personne passant sur le document.

2018-11-22 10:28 UTC, bboulesteix commented on LO.md
> +* de la communiquer, la reproduire, la copier ;
Ça me va. 👍 Super idée. Je propose que nous utilisions un _linter_ MarkDown, pour accorder nos violons en matière de syntaxe. De mon côté, je me sers de [linter-markdown](https://atom.io/packages/linter-markdown), dans Atom, un _linter_ qui respose justement sur [RemarkJS](https://github.com/remarkjs/remark-lint). 🙂 Je viens d’ailleurs de [passer le texte du fichier dans le linter](https://github.com/etalab/Licence-Ouverte/pull/2/commits/28ad2cf9f4a74733d3bed92691be9825085fcfa6). Comme tu dis, rien ne nous empêche ensuite d’écrire nos propres règles.

2018-11-22 10:37 UTC, bboulesteix commented
Merci pour ta réponse @noirbizarre.

Pour te répondre à mon tour en respectant tes catégories.

## Juridique

Je partage tes **resserves juridiques**, je m’avoue même fort incompétent en la matière. C‘est la raison pour laquelle j’ai posé la question au département juridique. 🔎 

Ensuite :

> Backporter ces modifications sur le document PDF du site Etalab ? (pour éviter d'avoir différentes versions)

Ça me semble être une bonne idée, oui. Et je veux bien m’en occuper, si nous décidons de nous engager dans cette voie. ✋ 

> Est-ce qu'il y a une procédure particulière pour faire reconnaître cette version modifiée comme la version en vigueur ? 

Je ne sais pas. 🤔 

## Technique

Je suis d’accord avec toi sur tout. 🙂 

> Ça n'est pas bloquant mais je me demande s'il ne serait pas nécéssaire pour le long terme d'exposer nos règles de gestion du markdown (syntaxe retenue de préférence et règles de rendu).

Avoir une moulinette qui puisse mettre un texte d’équerre sur le plan typographique ne serait pas de refus, oui, si c’est à cela que tu songes toi aussi. Dans le cas de sites statiques, ça peut même être fait au moment du _build_, je suppose.

2018-11-22 11:27 UTC, noirbizarre approved these changes

2018-11-22 11:28 UTC, noirbizarre commented
> > Backporter ces modifications sur le document PDF du site Etalab ? (pour éviter d'avoir différentes versions)

> Ça me semble être une bonne idée, oui. Et je veux bien m’en occuper, si nous décidons de nous engager dans cette voie. :hand:

Si on pouvait générer le pdf à partir de cette source automatiquement ça serait pas mal :thinking:

2018-11-22 11:34 UTC, bboulesteix commented
Merci pour le coup de tampon @noirbizarre.

> Si on pouvait générer le pdf à partir de cette source automatiquement ça serait pas mal 🤔

Je pense que [Pandoc](https://pandoc.org) peut faire ça, mais je ne suis pas certain de m’en servir sur ce coup.

2018-11-22 11:34 UTC, merged

2025-02-23 08:35 UTC, Nimesh199398 commented
bboulesteix:ajustements-typographiques